name: devcontainer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: [snail-runners]

    steps:
      - name: Install git
        run: sudo apt-get update && sudo apt-get install -y git

      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Build and test in devcontainer
        uses: devcontainers/ci@v0.3
        env:
          BUILDX_NO_DEFAULT_ATTESTATIONS: true
        with:
          runCmd: |
            cmake -B ./build -S ./ -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} && \
            cd ./build && make -j8 && ctest
