name: container

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: [snail-runners]

    steps:
      - name: Install git
        run: sudo apt-get update && sudo apt-get install -y git
  
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
  
      - name: Build the container
        run: docker build . --file ./docker/Dockerfile --tag localization-server:latest
  
      - name: Run the tests in the container
        run: |
          docker run --rm localization-server:latest \
          bash -c "cd ./build && ctest"