name: container

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: [self-hosted, linux, x64]
    steps:
    - name: Copy Runner Env to Workflow Env
      run: |
        echo "::add-mask::${LOCAL_REG_URL}"
        echo "::add-mask::${LOCAL_REG_USER}"
        echo "::add-mask::${LOCAL_REG_PASS}"
        echo "LOCAL_REG_URL=${LOCAL_REG_URL}" >> $GITHUB_ENV
        echo "LOCAL_REG_USER=${LOCAL_REG_USER}" >> $GITHUB_ENV
        echo "LOCAL_REG_PASS=${LOCAL_REG_PASS}" >> $GITHUB_ENV

    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        token: ${{ secrets.SUBMODULE_PAT }}

    - name: Docker Login to Local Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.LOCAL_REG_URL }}
        username: ${{ env.LOCAL_REG_USER }}
        password: ${{ env.LOCAL_REG_PASS }}

    - name: Build the Docker image
      run: docker build . --file ./docker/Dockerfile --tag ${{ env.LOCAL_REG_URL }}/secret-snail/localization-server:latest

    - name: Run the tests in the container
      run: |
        docker run --rm ${{ env.LOCAL_REG_URL }}/secret-snail/localization-server:latest \
        bash -c "cd ./build && ctest"

    - name: Push the Docker image
      run: docker push ${{ env.LOCAL_REG_URL }}/secret-snail/localization-server:latest
